/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoftwareSlugRouteImport } from './routes/software_.$slug'
import { Route as SupportCategorySlugRouteImport } from './routes/support_.category.$slug'
import { Route as DownloadsCategorySlugRouteImport } from './routes/downloads_.category.$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareSlugRoute = SoftwareSlugRouteImport.update({
  id: '/software_/$slug',
  path: '/software/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportCategorySlugRoute = SupportCategorySlugRouteImport.update({
  id: '/support_/category/$slug',
  path: '/support/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsCategorySlugRoute = DownloadsCategorySlugRouteImport.update({
  id: '/downloads_/category/$slug',
  path: '/downloads/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/request-demo': typeof RequestDemoRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/software': typeof SoftwareRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/support': typeof SupportRoute
  '/testimonials': typeof TestimonialsRoute
  '/software/$slug': typeof SoftwareSlugRoute
  '/downloads/category/$slug': typeof DownloadsCategorySlugRoute
  '/support/category/$slug': typeof SupportCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/request-demo': typeof RequestDemoRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/software': typeof SoftwareRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/support': typeof SupportRoute
  '/testimonials': typeof TestimonialsRoute
  '/software/$slug': typeof SoftwareSlugRoute
  '/downloads/category/$slug': typeof DownloadsCategorySlugRoute
  '/support/category/$slug': typeof SupportCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/request-demo': typeof RequestDemoRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/software': typeof SoftwareRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/support': typeof SupportRoute
  '/testimonials': typeof TestimonialsRoute
  '/software_/$slug': typeof SoftwareSlugRoute
  '/downloads_/category/$slug': typeof DownloadsCategorySlugRoute
  '/support_/category/$slug': typeof SupportCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/downloads'
    | '/faq'
    | '/industries'
    | '/partners'
    | '/request-demo'
    | '/request-quote'
    | '/services'
    | '/software'
    | '/success-stories'
    | '/support'
    | '/testimonials'
    | '/software/$slug'
    | '/downloads/category/$slug'
    | '/support/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/downloads'
    | '/faq'
    | '/industries'
    | '/partners'
    | '/request-demo'
    | '/request-quote'
    | '/services'
    | '/software'
    | '/success-stories'
    | '/support'
    | '/testimonials'
    | '/software/$slug'
    | '/downloads/category/$slug'
    | '/support/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/downloads'
    | '/faq'
    | '/industries'
    | '/partners'
    | '/request-demo'
    | '/request-quote'
    | '/services'
    | '/software'
    | '/success-stories'
    | '/support'
    | '/testimonials'
    | '/software_/$slug'
    | '/downloads_/category/$slug'
    | '/support_/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  PartnersRoute: typeof PartnersRoute
  RequestDemoRoute: typeof RequestDemoRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  ServicesRoute: typeof ServicesRoute
  SoftwareRoute: typeof SoftwareRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  SupportRoute: typeof SupportRoute
  TestimonialsRoute: typeof TestimonialsRoute
  SoftwareSlugRoute: typeof SoftwareSlugRoute
  DownloadsCategorySlugRoute: typeof DownloadsCategorySlugRoute
  SupportCategorySlugRoute: typeof SupportCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software_/$slug': {
      id: '/software_/$slug'
      path: '/software/$slug'
      fullPath: '/software/$slug'
      preLoaderRoute: typeof SoftwareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support_/category/$slug': {
      id: '/support_/category/$slug'
      path: '/support/category/$slug'
      fullPath: '/support/category/$slug'
      preLoaderRoute: typeof SupportCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads_/category/$slug': {
      id: '/downloads_/category/$slug'
      path: '/downloads/category/$slug'
      fullPath: '/downloads/category/$slug'
      preLoaderRoute: typeof DownloadsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  PartnersRoute: PartnersRoute,
  RequestDemoRoute: RequestDemoRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  ServicesRoute: ServicesRoute,
  SoftwareRoute: SoftwareRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  SupportRoute: SupportRoute,
  TestimonialsRoute: TestimonialsRoute,
  SoftwareSlugRoute: SoftwareSlugRoute,
  DownloadsCategorySlugRoute: DownloadsCategorySlugRoute,
  SupportCategorySlugRoute: SupportCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
